apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devops-microsservices-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/yousf3emad/devops-microservices-project/backend:82210154a0a7e0546656b212fdd11720f00e1392
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_NAME
          value: "appdb"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "password"
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: devops-microsservices-project
spec:
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000