apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: devops-microsservices-project
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: devops-microsservices-project
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
      id SERIAL PRIMARY KEY,
      name VARCHAR(100),
      email VARCHAR(100)
    );
    CREATE TABLE IF NOT EXISTS greetings (
      id SERIAL PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      message TEXT NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    INSERT INTO users (name, email)
    SELECT 'Ahmed Mohamed', 'ahmed@example.com'
    WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'ahmed@example.com');
    INSERT INTO users (name, email)
    SELECT 'Sara Ali', 'sara@example.com'
    WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'sara@example.com');
    INSERT INTO users (name, email)
    SELECT 'Mohamed Hassan', 'mohamed@example.com'
    WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'mohamed@example.com');
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: devops-microsservices-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: "appdb"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-script
        configMap:
          name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: devops-microsservices-project
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
